### ISSUE TITLE
problem with num_col and num_rows

### ISSUE THREAD

**Issue by hsauro** [sys-bio/teUtils#6]
If a user specifies a size less than the number of variables, eg with 6 variables if the user sets:

fitter.plotFit (num_col=2, num_row=2)

four graphs are generated but there is also an error

Traceback (most recent call last):

  File "D:\Documents\Tellurium\HellerstainExample.py", line 27, in <module>
    fitter.plotFit (num_col=2, num_row=2, figSize=(12, 6))

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\teUtils\model_fitter.py", line 249, in plotFit
    plotter.plotTimeSingle(self.fitted_ts, timeseries2=self.observed_ts, options=options, **kwargs)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\teUtils\timeseries_plotter.py", line 160, in plotTimeSingle
    ax = axes[row, col]

IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by joseph-hellerstein** [comment]
This should work now. The method overrides the users options so that all variables are plotted. If you want fewer, then you have to specify the "columns" option.
