### ISSUE TITLE
fitter.plotFit (num_col=1, num_row=1) doesn't work as expected

### ISSUE THREAD

**Issue by hsauro** [sys-bio/teUtils#7]
fitter.plotFit (num_col=1, num_row=1) d

yields an empty graph and the following error:

Traceback (most recent call last):

  File "D:\Documents\Tellurium\HellerstainExample.py", line 27, in <module>
    fitter.plotFit (num_col=1, num_row=1, figSize=(12, 6))

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\teUtils\model_fitter.py", line 249, in plotFit
    plotter.plotTimeSingle(self.fitted_ts, timeseries2=self.observed_ts, options=options, **kwargs)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\teUtils\timeseries_plotter.py", line 160, in plotTimeSingle
    ax = axes[row, col]

TypeError: 'AxesSubplot' object is not subscriptable

**Comment by joseph-hellerstein** [comment]
Try fitter.plotFit(num_col=1, num_row=1, is_multiple=True)
